### ISSUE TITLE
Error: "Do I know you?"

### ISSUE THREAD

**Issue by kamil-malinski** [daohoangson/bubby#5]
Hi!

I tried your bot and I ended up getting an error when I message the bot:

```console
  Error: Do I know you? #xxxxxxxxxx
       at assistantThreadIdUpsert (/root/bubby/packages/core/src/3rdparty/openai/assistant_thread.ts:46:11)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at sendReplies (/root/bubby/packages/core/src/handlers/reply_to_chat.ts:31:20)
       at allReplies (/root/bubby/packages/core/src/3rdparty/telegram/webhook.ts:59:3)
       at <anonymous> (/root/bubby/packages/core/src/3rdparty/telegram/webhook.ts:26:5)
       at execute (/root/bubby/node_modules/.pnpm/telegraf@4.15.0/node_modules/telegraf/lib/composer.js:501:17)
       at <anonymous> (/root/bubby/node_modules/.pnpm/telegraf@4.15.0/node_modules/telegraf/lib/composer.js:502:21)
       at execute (/root/bubby/node_modules/.pnpm/telegraf@4.15.0/node_modules/telegraf/lib/composer.js:501:17)
       at execute (/root/bubby/node_modules/.pnpm/telegraf@4.15.0/node_modules/telegraf/lib/composer.js:501:17)
       at <anonymous> (/root/bubby/node_modules/.pnpm/p-timeout@4.1.0/node_modules/p-timeout/index.js:50:13)
```

Where do I configure the whitelist of users, that are allowed to use the bot?

Thanks!

Kamil

**Comment by daohoangson** [comment]
You will need to change this line before deploying your bot: https://github.com/daohoangson/bubby/blob/e7db93b13532e2d734e006060278c137346c086e/packages/core/src/3rdparty/openai/assistant_thread.ts#L44-L47.

**Comment by kamil-malinski** [comment]
thanks, it worked!

**Comment by daohoangson** [comment]
That's great to hear. How was the conversation with the bot?

**Comment by kamil-malinski** [comment]
the conversation works great! I really like your bot, thanks a lot! I have just a few suggestions:

- please add the initial prompt into a config variable so one doesn't have to edit the source file
- enable streaming of the response

by the way, how does the memory feature work? could you please explain it briefly?

Cheers

Kamil

**Comment by kamil-malinski** [comment]
I see, thank you for the explanation!

maybe you could add "New thread." (and other commands?) as a command to the bot:

https://core.telegram.org/bots/features#commands

**Comment by daohoangson** [comment]
Yep, that makes sense.
